language: node_js

node_js:
  - "node"
  - "5"
  - "4"
  - "4.0"

script:
- npm run lint
- npm test
    
env:
  - CXX=g++-4.8
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8    